<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CleanupFieldsInShopifyOrdersTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table('shopify_orders', function (Blueprint $table) {
            $table->dropColumn('shopify_email');
            $table->dropColumn('shopify_created_at');
            $table->dropColumn('shopify_updated_at');
            $table->dropColumn('shopify_completed_at');
            $table->dropColumn('shopify_closed_at');
            $table->dropColumn('shopify_processed_at');
            $table->dropColumn('shopify_cancelled_at');
            $table->dropColumn('shopify_cancel_reason');
            $table->dropColumn('shopify_number');
            $table->dropColumn('shopify_note');
            $table->dropColumn('shopify_token');
            $table->dropColumn('shopify_gateway');
            $table->dropColumn('shopify_test');
            $table->dropColumn('shopify_total_price');
            $table->dropColumn('shopify_subtotal_price');
            $table->dropColumn('shopify_total_weight');
            $table->dropColumn('shopify_total_tax');
            $table->dropColumn('shopify_taxes_included');
            $table->dropColumn('shopify_currency');
            $table->dropColumn('shopify_financial_status');
            $table->dropColumn('shopify_confirmed');
            $table->dropColumn('shopify_total_discounts');
            $table->dropColumn('shopify_total_line_items_price');
            $table->dropColumn('shopify_cart_token');
            $table->dropColumn('shopify_buyer_accepts_marketing');
            $table->dropColumn('shopify_name');
            $table->dropColumn('shopify_referring_site');
            $table->dropColumn('shopify_landing_site');
            $table->dropColumn('shopify_total_price_usd');
            $table->dropColumn('shopify_checkout_token');
            $table->dropColumn('shopify_reference');
            $table->dropColumn('shopify_user_id');
            $table->dropColumn('shopify_location_id');
            $table->dropColumn('shopify_source_identifier');
            $table->dropColumn('shopify_source_url');
            $table->dropColumn('shopify_device_id');
            $table->dropColumn('shopify_phone');
            $table->dropColumn('shopify_customer_locale');
            $table->dropColumn('shopify_app_id');
            $table->dropColumn('shopify_browser_ip');
            $table->dropColumn('shopify_landing_site_ref');
            $table->dropColumn('shopify_order_number');
            $table->dropColumn('shopify_discount_applications');
            $table->dropColumn('shopify_discount_codes');
            $table->dropColumn('shopify_note_attributes');
            $table->dropColumn('shopify_payment_gateway_names');
            $table->dropColumn('shopify_processing_method');
            $table->dropColumn('shopify_checkout_id');
            $table->dropColumn('shopify_source_name');
            $table->dropColumn('shopify_fulfillment_status');
            $table->dropColumn('shopify_tax_lines');
            $table->dropColumn('shopify_tags');
            $table->dropColumn('shopify_contact_email');
            $table->dropColumn('shopify_order_status_url');
            $table->dropColumn('shopify_presentment_currency');
            $table->dropColumn('shopify_total_line_items_price_set');
            $table->dropColumn('shopify_total_discounts_set');
            $table->dropColumn('shopify_total_shipping_price_set');
            $table->dropColumn('shopify_subtotal_price_set');
            $table->dropColumn('shopify_total_price_set');
            $table->dropColumn('shopify_total_tax_set');
            $table->dropColumn('shopify_total_tip_received');
            $table->dropColumn('shopify_original_total_duties_set');
            $table->dropColumn('shopify_current_total_duties_set');
            $table->dropColumn('shopify_shipping_lines');
            $table->dropColumn('shopify_billing_address');
            $table->dropColumn('shopify_shipping_address');
            $table->dropColumn('shopify_client_details');
            $table->dropColumn('shopify_payment_details');
            $table->dropColumn('shopify_customer');
            $table->dropColumn('shopify_line_items');
            $table->dropColumn('shopify_fulfillments');
            $table->dropColumn('shopify_refunds');
            $table->dropColumn('shopify_customer_id');
            $table->json('data')->nullable();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('shopify_orders', function (Blueprint $table) {
            $table->string('shopify_email')->nullable();
            $table->string('shopify_created_at')->nullable();
            $table->string('shopify_updated_at')->nullable();
            $table->string('shopify_completed_at')->nullable();
            $table->string('shopify_closed_at')->nullable();
            $table->string('shopify_processed_at')->nullable();
            $table->string('shopify_cancelled_at')->nullable();
            $table->string('shopify_cancel_reason')->nullable();
            $table->integer('shopify_number')->unsigned();
            $table->string('shopify_note')->nullable();
            $table->string('shopify_token')->nullable();
            $table->string('shopify_gateway')->nullable();
            $table->boolean('shopify_test')->nullable();
            $table->string('shopify_total_price')->nullable();
            $table->string('shopify_subtotal_price')->nullable();
            $table->integer('shopify_total_weight')->unsigned();
            $table->string('shopify_total_tax')->nullable();
            $table->boolean('shopify_taxes_included');
            $table->string('shopify_currency')->nullable();
            $table->string('shopify_financial_status')->nullable();
            $table->boolean('shopify_confirmed');
            $table->string('shopify_total_discounts')->nullable();
            $table->string('shopify_total_line_items_price')->nullable();
            $table->string('shopify_cart_token')->nullable();
            $table->boolean('shopify_buyer_accepts_marketing');
            $table->string('shopify_name')->nullable();
            $table->string('shopify_referring_site')->nullable();
            $table->string('shopify_landing_site')->nullable();
            $table->string('shopify_total_price_usd')->nullable();
            $table->string('shopify_checkout_token')->nullable();
            $table->string('shopify_reference')->nullable();
            $table->string('shopify_user_id')->nullable();
            $table->string('shopify_location_id')->nullable();
            $table->string('shopify_source_identifier')->nullable();
            $table->string('shopify_source_url')->nullable();
            $table->string('shopify_device_id')->nullable();
            $table->string('shopify_phone')->nullable();
            $table->string('shopify_customer_locale')->nullable();
            $table->string('shopify_app_id')->nullable();
            $table->string('shopify_browser_ip')->nullable();
            $table->string('shopify_landing_site_ref')->nullable();
            $table->integer('shopify_order_number')->unsigned();
            $table->json('shopify_discount_applications')->nullable();
            $table->json('shopify_discount_codes')->nullable();
            $table->json('shopify_note_attributes')->nullable();
            $table->json('shopify_payment_gateway_names')->nullable();
            $table->string('shopify_processing_method')->nullable();
            $table->integer('shopify_checkout_id')->unsigned();
            $table->string('shopify_source_name')->nullable();
            $table->string('shopify_fulfillment_status')->nullable();
            $table->json('shopify_tax_lines')->nullable();
            $table->string('shopify_tags')->nullable();
            $table->string('shopify_contact_email')->nullable();
            $table->string('shopify_order_status_url')->nullable();
            $table->string('shopify_presentment_currency')->nullable();
            $table->json('shopify_total_line_items_price_set')->nullable();
            $table->json('shopify_total_discounts_set')->nullable();
            $table->json('shopify_total_shipping_price_set')->nullable();
            $table->json('shopify_subtotal_price_set')->nullable();
            $table->json('shopify_total_price_set')->nullable();
            $table->json('shopify_total_tax_set')->nullable();
            $table->string('shopify_total_tip_received')->nullable();
            $table->json('shopify_original_total_duties_set')->nullable();
            $table->json('shopify_current_total_duties_set')->nullable();
            $table->json('shopify_shipping_lines')->nullable();
            $table->json('shopify_billing_address')->nullable();
            $table->json('shopify_shipping_address')->nullable();
            $table->json('shopify_client_details')->nullable();
            $table->json('shopify_payment_details')->nullable();
            $table->json('shopify_customer')->nullable();
            $table->json('shopify_line_items')->nullable();
            $table->json('shopify_fulfillments')->nullable();
            $table->json('shopify_refunds')->nullable();
            $table->unsignedInteger('shopify_customer_id');
            $table->dropColumn('data');
        });
    }
}
